### ISSUE TITLE
No config.js file for the node proxy server

### ISSUE THREAD

**Issue by mattcremerband** [McFizh/magento2-react#7]
Hi McFizh, I'm having trouble getting the proxy to start, there seems to be a missing config.js file in the vagrant/proxy folder that's needed by index.js
Have I missed a step that creates this file?

**Comment by McFizh** [comment]
config.js file is created by vagrant using this script:

https://github.com/McFizh/magento2-react/blob/master/VagrantScripts/tools/integration.php

Script creates integration config for m2 and then fetches keys to node.js server.  And that script is in turn called in file:

https://github.com/McFizh/magento2-react/blob/master/VagrantScripts/base.sh

in line 123
